apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portfolio-java.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "portfolio-java.name" . }}
    app.kubernetes.io/part-of: private-banking-platform-lab
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
