---
all:
  children:
    okd_lbs:
      hosts:
        okd-lb:
          ansible_host: "{{ okd_lb_ansible_host }}"
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/private-banking-openstack-workloads
