{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.quota.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo3tier.commonLabels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
spec:
  hard:
    {{- toYaml .Values.quota.hard | nindent 4 }}
{{- end }}
